#!/bin/sh

javac sentenceID.java
java sentenceID app_siddharth.txt app
java sentenceID camera_siddharth.txt cam
java sentenceID headphones_siddharth.txt hea
java sentenceID home_appliances_siddharth.txt hom
java sentenceID laptop_siddharth.txt lap
java sentenceID mobile_siddharth.txt mob
java sentenceID movies_siddharth.txt mov
java sentenceID smartwatch_siddharth.txt sma
java sentenceID speaker_siddharth.txt spe
java sentenceID tablet_siddharth.txt tab
java sentenceID travel_siddharth.txt tra
java sentenceID tv_siddharth.txt tel

cat *.txt >> id_all.txt

javac CreateXML.java
java CreateXML id_all.txt  
