#!/bin/sh
rm -r ../annotated_siddharth/build
mkdir ../annotated_siddharth/build
cp ./*.java ../annotated_siddharth/build
cd ../annotated_siddharth/build
cp ../*.txt .

cat id_*.txt >> id_all.txt

javac CreateXML.java
java CreateXML id_all.txt  

rm *.class *.java 

rm id_app_siddharth.txt id_camera_siddharth.txt id_headphones_siddharth.txt \
id_home_appliances_siddharth.txt id_laptop_siddharth.txt id_mobile_siddharth.txt \
id_movies_siddharth.txt id_smartwatch_siddharth.txt id_speaker_siddharth.txt \
id_tablet_siddharth.txt id_travel_siddharth.txt id_tv_siddharth.txt
